### ISSUE TITLE
Problema ao tentar converter uma data com código inválido

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/scielo_scholarly_data#48]
Ocorre um bug ao tentar chamar o método convert_to_iso_date com um valor não numérico, por exemplo: `003B`. Veja o que ocorre ao chamar `convert_to_iso_date('003B')`:

```
Traceback (most recent call last):
  File "/home/rafaeljpd/.virtualenvs/scielo-cited-references/src/scielo-scholarly-data/scielo_scholarly_data/core.py", line 250, in convert_to_iso_date
    text = parse(text).date()
  File "/home/rafaeljpd/.virtualenvs/scielo-cited-references/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/rafaeljpd/.virtualenvs/scielo-cited-references/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 003B

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rafaeljpd/Dropbox/repos/scielo/cited-references/core/matchers/enrich_references.py", line 291, in <module>
    main()
  File "/home/rafaeljpd/Dropbox/repos/scielo/cited-references/core/matchers/enrich_references.py", line 116, in main
    cited_year_cleaned = str(standardizer.document_publication_date(cit.cited_year, only_year=True))
  File "/home/rafaeljpd/.virtualenvs/scielo-cited-references/src/scielo-scholarly-data/scielo_scholarly_data/standardizer.py", line 429, in document_publication_date
    text = convert_to_iso_date(text, day, month, only_year)
  File "/home/rafaeljpd/.virtualenvs/scielo-cited-references/src/scielo-scholarly-data/scielo_scholarly_data/core.py", line 270, in convert_to_iso_date
    month = MONTHS_DICT[month]
KeyError: ''
```

Sugiro que na situação em que ocorre ParserError, o método retorne uma string vazia. E isso deve ser inserido próximo antes da linha que trata a exceção ValueError: https://github.com/scieloorg/scielo_scholarly_data/blob/356016f68fbc66ec8f2852ebcdfa1bc419bc5636/scielo_scholarly_data/core.py#L251

Como o erro pode ser replicado:
```python
from scielo_scholarly_data import core
core.convert_to_iso_date('003B')
```

**Comment by rafaelpezzuto** [comment]
Resolvido por #51
