### ISSUE TITLE
Teste não executa devido a erro de sintaxe

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/scielo_scholarly_data#49]
### Descrição do problema
Ao executar `python setup.py test` ocorre erro de sintaxe, como descrito no log seguinte:

```bash
Traceback (most recent call last):
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/setup.py", line 8, in <module>
    setup(
  File "/home/rafaeljpd/.local/share/virtualenvs/scielo-scholarly-data/lib/python3.9/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/rafaeljpd/.local/share/virtualenvs/scielo-scholarly-data/lib/python3.9/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/home/rafaeljpd/.local/share/virtualenvs/scielo-scholarly-data/lib/python3.9/site-packages/setuptools/command/test.py", line 255, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.9/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.9/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/rafaeljpd/.local/share/virtualenvs/scielo-scholarly-data/lib/python3.9/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/rafaeljpd/Dropbox/repos/scielo/scielo_scholarly_data/tests/test_standardizer.py", line 876
    def test_book_title_for_deduplication_html_entities_keeps(self):
    ^
SyntaxError: invalid syntax
```

### Passos para reproduzir o problema
1. Clone o repostiório
2. Construa um ambiente virtual (`virtualenv -p python .venv`) 
3. Instale os requirements (`source .venv/activate/bin && pip install -r requirements.txt`)
4. Instale o pacote (`pip setup.py install`)
5. Execute os testes (`python setup.py test`)
6. Observe o erro apresentado

### Comportamento esperado
É esperado que nenhum erro ocorra (principalmente de sintaxe)

### Screenshots ou vídeos
Vide descrição inicial da Issue

### Anexos
N/A

### Ambiente utilizado
- Linux Kubuntu 21.10
- Kernel 5.14.9-051409-generic
- Python 3.9.7

**Comment by ednilson** [comment]
Fixed #50
